# -*- coding: utf-8 -*-
"""Chocolate Sales Data Analysis Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nyg9qvutqPPUMdOoMzzHJ1y90gi_T-kM
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv("Chocolate Sales (1).csv")

df["Amount"] = (
    df["Amount"]
    .replace(r'[\$,]', '', regex=True)
    .astype(float)
)

#Total_Boxes

Total_boxes=df["Boxes Shipped"].sum()
print(f"Total no of boxes sold: {Total_boxes}")

#Total Sales

Total_sales=df["Amount"].sum()
print(f"Total sales data {Total_sales}")

#Average sales

avg_sales=df["Amount"].mean()
print(f"Average sales data {avg_sales}")

#Calculating Total sales by country

Total_sales_country=df.groupby("Country")["Amount"].sum()

print(f"Total Sales by Country: {Total_sales_country}")

#Calculating Total sales by product

Total_sales_product=df.groupby("Product")["Amount"].sum()

print(f"Total Sales by Product: $ {Total_sales_product}")

#Calculating Total sales by salesperson

Sales_by_salesperson=df.groupby("Sales Person")["Amount"].sum()

print(f"Total Sales by Salesperson: {Sales_by_salesperson}")

#Decision Making on Bonus

df["Sales_by_salesperson"]=df.groupby("Sales Person")["Amount"].transform("sum")

df["Bonus_for_sales"] = df["Sales_by_salesperson"].apply(
    lambda x: "20% Bonus" if x > 50000 else "No Bonus")

print(df)

#Calculating top 3 products

Top_3_product = df.groupby("Product")["Amount"].sum().head(3)

print("Top_3_product:", Top_3_product)

df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)
df["Year"] = df["Date"].dt.year

yearly_sales = df.groupby("Year")["Amount"].sum()

yoy_growth = yearly_sales.pct_change() * 100
print(yoy_growth)

# Visualization of the Total sales by country

plt.figure(figsize=(12,6))
plt.bar(Total_sales_country.index,Total_sales_country.values, color="Blue")

plt.title("Total_sales_country")
plt.xlabel("Country")
plt.ylabel("Total_sales_country")
plt.xticks(rotation=45)

plt.show()

# Visualization of the Total sales by product

plt.figure(figsize=(12,6))

plt.barh(
    Total_sales_product.index,
    Total_sales_product.values,
    color="orange"
)

plt.title("Total_sales_product")
plt.xlabel("Total_sales_product")

plt.show()

# Visualization of the Total sales by salesperson

plt.figure(figsize=(12,6))
plt.bar(Sales_by_salesperson.index,Sales_by_salesperson.values, color="Blue")

plt.title("Sales_by_salesperson")
plt.xlabel("Sales Person")
plt.ylabel("Sales_by_salesperson")
plt.xticks(rotation=45, ha='right')

plt.show()